### ISSUE TITLE
Create scripts for MHR

### ISSUE THREAD

**Issue by sordonia** [microsoft/mttl#37]
```[tasklist]
### Tasks
- [x] Create scripts for T0 training / test LoRA
- [x] Create scripts for T0 training / test Poly
- [x] Create scripts for T0 training / test MHR
- [ ] Create scripts for NI training / test MHR
```
